# Generated by Django 2.2.8 on 2023-10-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email_Adress', models.EmailField(max_length=100)),
                ('physical_Address', models.CharField(max_length=100)),
            ],
        ),
    ]
