# Generated by Django 2.2.8 on 2023-11-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
    ]
