# Generated by Django 4.2.7 on 2023-11-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_registereduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email_Adress', models.EmailField(max_length=100)),
                ('physical_Address', models.CharField(max_length=100)),
            ],
        ),
    ]
