# Generated by Django 3.2.14 on 2023-11-04 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerduser',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='registerduser',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='registerduser',
            name='email_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
